### ISSUE TITLE
insufficient_quota error

### ISSUE THREAD

**Issue by kcamnairb** [nitefood/ai-bash-gpt#1]
I've been getting this error for the last couple of weeks whenever I try to us ai. I even made a new openai key and stored it in ~/.openai.key. I don't use the api in any other software so I don't see how I would have exceeded the quota.
```
ai "how many planets are there in the solar system?"

- API ERROR -
 TYPE  insufficient_quota
 CODE  null
 MESG  You exceeded your current quota, please check your plan and billing details.
ChatGPT error. Retrying in 2 seconds (press CTRL-C to cancel)...
```

**Comment by aivanise** [comment]
FWIW, I had the same problem and even switched to the paid plan as I thought I've really wasted all of my free credits. At the end I've just downloaded the latest copy from master and it all started working again.

**Comment by nitefood** [comment]
hey @kcamnairb,

all the API errors are all directly from OpenAI, the `ai` script simply shows it to you as they are sent from the API endpoint. My guess is that, unless you've actually used up all your [free trial credit](https://platform.openai.com/account/usage), there's some sort of request throttling quota. That would also explain the temporary error in @aivanise's case.

**Comment by nitefood** [comment]
Further observation:

on a free account, I am still below the 18$ free credit grant, but it reports expired on April 1st.
API keys created before April 1st will work without problems.

So today (April 23rd) I created a new API key on this same account, and switched to it. I will get that same `insufficient_quota` error.

Could you guys verify if this is the case with your keys too?

So if you guys were using free keys

**Comment by aivanise** [comment]
It's still working for me, but im not on a free account any more

» are you still working


╭───────────╮
╞  ChatGPT  ╡
╰───────────╯

  Yes, I am still here and working. How can I assist you?

:)

**Comment by nitefood** [comment]
I may add a switch (something like, say `-4`) to add on-demand gpt4 support. Any interest in that option?

**Comment by aivanise** [comment]
Yes, please, definitely. Do i have to have openai+ or is it just using more credits?

**Comment by nitefood** [comment]
You need an API key from a paid plan for it to work, otherwise OpenAI will respond with an error saying the model does not exist. Moreover, AFAIK you only get a limited number of GPT-4 interactions per day, even as a paying user. Not sure if this policy has changed recently, since I don't have a paid plan - I am from Italy (which banned ChatGPT for the time being). So I just added the `-4` option to make it use the `gpt-4` model instead of the default `gpt-3.5-turbo` one.

I'd be glad if you could test it out and let me know if it works! **But please bear in mind that interactions with the GPT-4 model likely cost more than those with GPT-3.5. Please do your own research before using the `-4` switch**!

From the [API documentation](https://platform.openai.com/docs/models/gpt-4), I also see they have a `gpt-4-32k` model which supports 4x the current context size (i.e. can remember a lot more of the conversation, supports way larger inputs, etc), which could probably be a desirable option as well. Let me known your thoughts.

I just pushed a test version of the script in the [gpt4-support branch](https://github.com/nitefood/ai-bash-gpt/tree/gpt4-support).

**Comment by aivanise** [comment]
eh, looks like paid api plan is not enough, you have to have openai+, at least I don't see anywhere were I could turn gpt-4 on or off

- API ERROR -
 TYPE  invalid_request_error
 CODE  model_not_found
 MESG  The model: `gpt-4` does not exist

**Comment by nitefood** [comment]
I see, thanks for trying. I misunderstood your question, and thought you were on ChatGPT+ subscription already - instead if I get it right, you set up billing and can consume their GPT-3 API on a pay-per-use basis, correct?

Anyway, it looks like GPT-4 API access can be requested [here](https://openai.com/waitlist/gpt-4-api), could be worth a shot to see if they let you in. Not really sure what their policy is at the moment...

**Comment by aivanise** [comment]
ok, requested it, pu the url to this repo as the reason, lets see how it goes ;)

**Comment by nitefood** [comment]
great, thanks for taking the time. I'm gonna close this issue now, but please share any progress in the [discussion](https://github.com/nitefood/ai-bash-gpt/discussions/2) I just opened
